
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { BookOpenIcon, LanguagesIcon, PlusIcon, BookIcon, WebcamIcon } from "lucide-react"

export default function Dashboard() {
  return (
    <div className="flex flex-col min-h-screen bg-muted/40">
      <main className="flex-1 grid gap-4 p-4 md:gap-8 md:p-10 hover:*:*:cursor-pointer hover:*:*:shadow-xl">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 md:gap-8">

          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <LanguagesIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Vocabulary in Context</CardTitle>
                <CardDescription>Master new words and phrases with flashcards based on words only you know</CardDescription>
              </div>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <BookIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>AI Generated Stories</CardTitle>
                <CardDescription>Read stories generated by AI based on your interests and vocabulary</CardDescription>
              </div>
            </CardHeader>

          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <WebcamIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Conversation Practice</CardTitle>
                <CardDescription>Practice speaking with AI-generated conversations based on your vocabulary</CardDescription>
              </div>
            </CardHeader>

          </Card>

        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-8">

          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle>Paragraphs Read</CardTitle>
              <div className="bg-muted rounded-full flex items-center justify-center aspect-square w-10 md:w-12">
                <BookOpenIcon className="w-5 h-5" />
              </div>
            </CardHeader>
            <CardContent>
              {/* <LineChart className="w-full aspect-[4/3]" /> */}
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle>Add New Flashcards</CardTitle>
              <div className="bg-muted rounded-full flex items-center justify-center aspect-square w-10 md:w-12">
                <PlusIcon className="w-5 h-5" />
              </div>
            </CardHeader>
            <CardContent>
              {/* <LineChart className="w-full aspect-square" /> */}
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle>Vocabulary Generated in Context</CardTitle>
              <div className="bg-muted rounded-full flex items-center justify-center aspect-square w-10 md:w-12">
                <LanguagesIcon className="w-5 h-5" />
              </div>
            </CardHeader>
            <CardContent>
              {/* <LineChart className="w-full aspect-[4/3]" /> */}
            </CardContent>
          </Card>

        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-8">

          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle>Lessons Completed</CardTitle>
              <div className="bg-muted rounded-full flex items-center justify-center aspect-square w-10 md:w-12">
                <BookOpenIcon className="w-5 h-5" />
              </div>
            </CardHeader>
            <CardContent>
              {/* <LineChart className="w-full aspect-[4/3]" /> */}
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle>Proficiency Levels</CardTitle>
              <div className="bg-muted rounded-full flex items-center justify-center aspect-square w-10 md:w-12">
                <PlusIcon className="w-5 h-5" />
              </div>
            </CardHeader>
            <CardContent>
              {/* <LineChart className="w-full aspect-square" /> */}
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle>Vocabulary Generated in Context</CardTitle>
              <div className="bg-muted rounded-full flex items-center justify-center aspect-square w-10 md:w-12">
                <LanguagesIcon className="w-5 h-5" />
              </div>
            </CardHeader>
            <CardContent>
              {/* <LineChart className="w-full aspect-[4/3]" /> */}
            </CardContent>
          </Card>

        </div>
      </main>
    </div>
  )
}